### ISSUE TITLE
Suggestions & Two issues:

### ISSUE THREAD

**Issue by inukaze** [0ldsk00l/nestopia#278]
Hi there wonderful job with this emulator. i just want give you some ideas

1. Make more compatible with older distributions If possible try to use automake 1.10 or older, i can't compile under Devuan Jessie because

```
$ autoreconf -vif
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
/usr/share/aclocal/libstroke.m4:29: warning: underquoted definition of smr_ARG_WITHLIB
/usr/share/aclocal/libstroke.m4:29:   run info Automake 'Extending aclocal'
/usr/share/aclocal/libstroke.m4:29:   or see http://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:119: error: require Automake 1.15, but have 1.14.1
autoreconf: automake failed with exit status: 1

```
i relly don't want to download and compile newer version of automake, and i don't want install Debian Stretch or something more actual. 

Because i trust more in older software for the system stability. But the gamers ever had that problem on choose older distro for stability of newer distros rolling release, because the developers don't stop to put newer dependencies 

Well i must do, because this software need a newer version ¬¬
Ok i had download the Automake 1.16, and run again : 

```
$ autoreconf -vif
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
/usr/share/aclocal/libstroke.m4:29: warning: underquoted definition of smr_ARG_WITHLIB
/usr/share/aclocal/libstroke.m4:29:   run info Automake 'Extending aclocal'
/usr/share/aclocal/libstroke.m4:29:   or see https://www.gnu.org/software/automake/manual/automake.html#Extending-aclocal
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
configure.ac:22: installing './config.guess'
configure.ac:22: installing './config.sub'
configure.ac:119: installing './install-sh'
configure.ac:119: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'

$ ./configure --prefix=/usr
checking whether configure should try to set CXXFLAGS/CPPFLAGS/LDFLAGS... yes
./configure: line 1898: AX_CHECK_ENABLE_DEBUG: command not found
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
./configure: line 2020: AX_COMPILER_VENDOR: command not found
./configure: line 2021: AX_COMPILER_VERSION: command not found
checking for a sed that does not truncate output... /bin/sed
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
./configure: line 2603: syntax error near unexpected token `${cxxflags_test}'
./configure: line 2603: `	AX_APPEND_COMPILE_FLAGS(${cxxflags_test} -Wno-narrowing, CXXFLAGS)'
```

Well i can't compile your source code from git under Devuan Jessie 1.0

2. Add RetroAchivement Support

3. Add when the user Maximize the window, the image can be stretch to fit window content, can be should add "Aspect Ratio : Disable" for don't core things like -> 4:3, 16:9, 16:10, etc. . . 

4. Well with the version repository i had an issue, when i mapped my Xbox 360 Controller, the emulator don't took the changes i made, evers read the defaults buttons mapping.

Thanks for readme.

**Comment by orbea** [comment]
For the second issue you are missing `autoconf-archive`. I ran into this recently too...
https://github.com/0ldsk00l/nestopia/issues/276

**Comment by inukaze** [comment]
Hi there, for fix that, is dependence missing, i just installed the follow packages : 

```
autoconf-archive
libepoxy-dev
```

and now

```
[nestopia]$ ./configure --prefix=/usr
checking whether configure should try to set CXXFLAGS/CPPFLAGS/LDFLAGS... yes
./configure: line 1944: AX_CHECK_ENABLE_DEBUG: command not found
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for C++ compiler vendor... gnu
./configure: line 2631: AX_COMPILER_VERSION: command not found
checking for a sed that does not truncate output... /bin/sed
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for ZLIB... yes
checking for LIBARCHIVE... yes
checking for SDL2... yes
checking for LIBEPOXY... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports the include directive... yes (GNU style)
checking whether make supports nested variables... yes
checking dependency style of g++... gcc3
checking whether make supports nested variables... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands

	nestopia 1.49-WIP
	Using gnu, 

	CXX:        g++
	CXXFLAGS:   -g -O2
	CPPFLAGS:   
	LDFLAGS:    

[nestopia]$ make
  CXX      source/core/nestopia-NstAssert.o
  CXX      source/core/nestopia-NstCartridgeInes.o
  CXX      source/core/nestopia-NstFile.o
  CXX      source/core/nestopia-NstVideoFilterxBR.o
  CXX      source/core/nestopia-NstVideoFilterNone.o
  CXX      source/core/nestopia-NstPatcherUps.o
  CXX      source/core/input/nestopia-NstInpTopRider.o
  CXX      source/core/input/nestopia-NstInpCrazyClimber.o
  CXX      source/core/input/nestopia-NstInpPowerGlove.o
  CXX      source/core/input/nestopia-NstInpOekaKidsTablet.o
  CXX      source/core/input/nestopia-NstInpMouse.o
  CXX      source/core/input/nestopia-NstInpFamilyTrainer.o
  CXX      source/core/input/nestopia-NstInpPartyTap.o
  CXX      source/core/input/nestopia-NstInpMahjong.o
  CXX      source/core/input/nestopia-NstInpTurboFile.o
  CXX      source/core/input/nestopia-NstInpBarcodeWorld.o
  CXX      source/core/input/nestopia-NstInpPad.o
  CXX      source/core/input/nestopia-NstInpFamilyKeyboard.o
  CXX      source/core/input/nestopia-NstInpAdapter.o
  CXX      source/core/input/nestopia-NstInpRob.o
  CXX      source/core/input/nestopia-NstInpDoremikkoKeyboard.o
  CXX      source/core/input/nestopia-NstInpPachinko.o
  CXX      source/core/input/nestopia-NstInpKonamiHyperShot.o
  CXX      source/core/input/nestopia-NstInpZapper.o
  CXX      source/core/input/nestopia-NstInpHoriTrack.o
  CXX      source/core/input/nestopia-NstInpExcitingBoxing.o
  CXX      source/core/input/nestopia-NstInpPowerPad.o
  CXX      source/core/input/nestopia-NstInpSuborKeyboard.o
  CXX      source/core/input/nestopia-NstInpPokkunMoguraa.o
  CXX      source/core/input/nestopia-NstInpBandaiHyperShot.o
  CXX      source/core/input/nestopia-NstInpPaddle.o
  CXX      source/core/nestopia-NstStream.o
  CXX      source/core/vssystem/nestopia-NstVsSuperXevious.o
  CXX      source/core/vssystem/nestopia-NstVsRbiBaseball.o
  CXX      source/core/vssystem/nestopia-NstVsTkoBoxing.o
  CXX      source/core/vssystem/nestopia-NstVsSystem.o
  CXX      source/core/nestopia-NstTracker.o
  CXX      source/core/nestopia-NstXml.o
  CXX      source/core/nestopia-NstProperties.o
  CXX      source/core/nestopia-NstCpu.o
  CXX      source/core/nestopia-NstVideoRenderer.o
  CXX      source/core/nestopia-NstPatcherIps.o
  CXX      source/core/nestopia-NstTrackerRewinder.o
  CXX      source/core/nestopia-NstVector.o
  CXX      source/core/nestopia-NstLog.o
  CXX      source/core/nestopia-NstSoundPlayer.o
  CXX      source/core/nestopia-NstSoundRenderer.o
  CXX      source/core/nestopia-NstCartridge.o
  CXX      source/core/nestopia-NstChips.o
  CXX      source/core/nestopia-NstApu.o
  CXX      source/core/nestopia-NstVideoFilterHqX.o
  CXX      source/core/nestopia-NstSha1.o
  CXX      source/core/nestopia-NstRam.o
  CXX      source/core/nestopia-NstState.o
  CXX      source/core/api/nestopia-NstApiVideo.o
  CXX      source/core/api/nestopia-NstApiCheats.o
  CXX      source/core/api/nestopia-NstApiCartridge.o
  CXX      source/core/api/nestopia-NstApiMovie.o
  CXX      source/core/api/nestopia-NstApiTapeRecorder.o
  CXX      source/core/api/nestopia-NstApiEmulator.o
  CXX      source/core/api/nestopia-NstApiRewinder.o
  CXX      source/core/api/nestopia-NstApiNsf.o
  CXX      source/core/api/nestopia-NstApiFds.o
  CXX      source/core/api/nestopia-NstApiMachine.o
  CXX      source/core/api/nestopia-NstApiDipSwitches.o
  CXX      source/core/api/nestopia-NstApiUser.o
  CXX      source/core/api/nestopia-NstApiBarcodeReader.o
  CXX      source/core/api/nestopia-NstApiInput.o
  CXX      source/core/api/nestopia-NstApiSound.o
  CXX      source/core/nestopia-NstVideoScreen.o
  CXX      source/core/nestopia-NstCheats.o
  CXX      source/core/nestopia-NstZlib.o
  CXX      source/core/nestopia-NstCartridgeUnif.o
  CXX      source/core/nestopia-NstCore.o
  CXX      source/core/nestopia-NstImage.o
  CXX      source/core/nestopia-NstVideoFilter2xSaI.o
  CXX      source/core/nestopia-NstMemory.o
  CXX      source/core/nestopia-NstImageDatabase.o
  CXX      source/core/nestopia-NstMachine.o
  CXX      source/core/nestopia-NstPins.o
  CXX      source/core/nestopia-NstPpu.o
  CXX      source/core/nestopia-NstTrackerMovie.o
  CXX      source/core/nestopia-NstPatcher.o
  CXX      source/core/board/nestopia-NstBoardVsSystem.o
  CXX      source/core/board/nestopia-NstBoardBmc72in1.o
  CXX      source/core/board/nestopia-NstBoardUnlTf1201.o
  CXX      source/core/board/nestopia-NstBoardBmcResetBased4in1.o
  CXX      source/core/board/nestopia-NstBoardBmc20in1.o
  CXX      source/core/board/nestopia-NstBoardKonamiVrc6.o
  CXX      source/core/board/nestopia-NstBoardKonamiVrc2.o
  CXX      source/core/board/nestopia-NstBoardSachenS8259.o
  CXX      source/core/board/nestopia-NstBoardJalecoJf17.o
  CXX      source/core/board/nestopia-NstBoardBmcVrc4.o
  CXX      source/core/board/nestopia-NstBoardWaixingSgzlz.o
  CXX      source/core/board/nestopia-NstBoardUnlA9746.o
  CXX      source/core/board/nestopia-NstBoardNamcot175.o
  CXX      source/core/board/nestopia-NstBoardCamerica.o
  CXX      source/core/board/nestopia-NstBoardJalecoJf16.o
  CXX      source/core/board/nestopia-NstBoardTxc.o
  CXX      source/core/board/nestopia-NstBoardDiscrete.o
  CXX      source/core/board/nestopia-NstBoardAveD1012.o
  CXX      source/core/board/nestopia-NstBoard.o
  CXX      source/core/board/nestopia-NstBoardBmcPowerjoy84in1.o
  CXX      source/core/board/nestopia-NstBoardTaitoX1005.o
  CXX      source/core/board/nestopia-NstBoardBtlMarioBaby.o
  CXX      source/core/board/nestopia-NstBoardMmc3.o
  CXX      source/core/board/nestopia-NstBoardWaixingZs.o
  CXX      source/core/board/nestopia-NstBoardBmc36in1.o
  CXX      source/core/board/nestopia-NstBoardWaixingSecurity.o
  CXX      source/core/board/nestopia-NstBoardBmcGoldenGame260in1.o
  CXX      source/core/board/nestopia-NstBoardBtl6035052.o
  CXX      source/core/board/nestopia-NstBoardNitra.o
  CXX      source/core/board/nestopia-NstBoardHosenkan.o
  CXX      source/core/board/nestopia-NstBoardUnlSuperFighter3.o
  CXX      source/core/board/nestopia-NstBoardBmcSuperGun20in1.o
  CXX      source/core/board/nestopia-NstBoardBmc9999999in1.o
  CXX      source/core/board/nestopia-NstBoardFfe.o
  CXX      source/core/board/nestopia-NstBoardBmcA65as.o
  CXX      source/core/board/nestopia-NstBoardMmc5.o
  CXX      source/core/board/nestopia-NstBoardMmc2.o
  CXX      source/core/board/nestopia-NstBoardIremHolyDiver.o
  CXX      source/core/board/nestopia-NstBoardBmc21in1.o
  CXX      source/core/board/nestopia-NstBoardBmc8157.o
  CXX      source/core/board/nestopia-NstBoardGouder.o
  CXX      source/core/board/nestopia-NstBoardBtlPikachuY2k.o
  CXX      source/core/board/nestopia-NstBoardCaltron.o
  CXX      source/core/board/nestopia-NstBoardUnlKingOfFighters97.o
  CXX      source/core/board/nestopia-NstBoardBmcNovelDiamond.o
  CXX      source/core/board/nestopia-NstBoardSunsoftDcs.o
  CXX      source/core/board/nestopia-NstBoardTxRom.o
  CXX      source/core/board/nestopia-NstBoardBmcY2k64in1.o
  CXX      source/core/board/nestopia-NstBoardTxcTw.o
  CXX      source/core/board/nestopia-NstBoardTengen.o
  CXX      source/core/board/nestopia-NstBoardUnlCc21.o
  CXX      source/core/board/nestopia-NstBoardBxRom.o
  CXX      source/core/board/nestopia-NstBoardBandaiOekaKids.o
  CXX      source/core/board/nestopia-NstBoardOpenCorp.o
  CXX      source/core/board/nestopia-NstBoardMmc4.o
  CXX      source/core/board/nestopia-NstBoardSachenSa72008.o
  CXX      source/core/board/nestopia-NstBoardKonamiVrc1.o
  CXX      source/core/board/nestopia-NstBoardDreamtech.o
  CXX      source/core/board/nestopia-NstBoardBandaiAerobicsStudio.o
  CXX      source/core/board/nestopia-NstBoardCxRom.o
  CXX      source/core/board/nestopia-NstBoardBmc64in1.o
  CXX      source/core/board/nestopia-NstBoardJalecoJf11.o
  CXX      source/core/board/nestopia-NstBoardBtlGeniusMerioBros.o
  CXX      source/core/board/nestopia-NstBoardSubor.o
  CXX      source/core/board/nestopia-NstBoardIremG101.o
  CXX      source/core/board/nestopia-NstBoardIremKaiketsu.o
  CXX      source/core/board/nestopia-NstBoardWaixingPs2.o
  CXX      source/core/board/nestopia-NstBoardBmcSuper700in1.o
  CXX      source/core/board/nestopia-NstBoardSunsoft5b.o
  CXX      source/core/board/nestopia-NstBoardNtdec.o
  CXX      source/core/board/nestopia-NstBoardBmcSuperHiK300in1.o
  CXX      source/core/board/nestopia-NstBoardBmcHero.o
  CXX      source/core/board/nestopia-NstBoardWaixingSgz.o
  CXX      source/core/board/nestopia-NstBoardBmc35in1.o
  CXX      source/core/board/nestopia-NstBoardBtlSmb2b.o
  CXX      source/core/board/nestopia-NstBoardSunsoft1.o
  CXX      source/core/board/nestopia-NstBoardUxRom.o
  CXX      source/core/board/nestopia-NstBoardBenshengBs5.o
  CXX      source/core/board/nestopia-NstBoardFujiya.o
  CXX      source/core/board/nestopia-NstBoardBandai24c0x.o
  CXX      source/core/board/nestopia-NstBoardSachen74x374.o
  CXX      source/core/board/nestopia-NstBoardWaixingSh2.o
  CXX      source/core/board/nestopia-NstBoardBmc76in1.o
  CXX      source/core/board/nestopia-NstBoardBmcSuper24in1.o
  CXX      source/core/board/nestopia-NstBoardJalecoSs88006.o
  CXX      source/core/board/nestopia-NstBoardIremLrog017.o
  CXX      source/core/board/nestopia-NstBoardSuperGameLionKing.o
  CXX      source/core/board/nestopia-NstBoardBmc800in1.o
  CXX      source/core/board/nestopia-NstBoardUnlEdu2000.o
  CXX      source/core/board/nestopia-NstBoardAcclaimMcAcc.o
  CXX      source/core/board/nestopia-NstBoardTxcMxmdhtwo.o
  CXX      source/core/board/nestopia-NstBoardBmcCtc65.o
  CXX      source/core/board/nestopia-NstBoardSuperGameBoogerman.o
  CXX      source/core/board/nestopia-NstBoardBtlSmb2a.o
  CXX      source/core/board/nestopia-NstBoardKaiser.o
  CXX      source/core/board/nestopia-NstBoardBmcT262.o
  CXX      source/core/board/nestopia-NstBoardSachenTcu.o
  CXX      source/core/board/nestopia-NstBoardKonamiVrc4.o
  CXX      source/core/board/nestopia-NstBoardJalecoJf13.o
  CXX      source/core/board/nestopia-NstBoardKayPandaPrince.o
  CXX      source/core/board/nestopia-NstBoardTaitoX1017.o
  CXX      source/core/board/nestopia-NstBoardHes.o
  CXX      source/core/board/nestopia-NstBoardSachenStreetHeroes.o
  CXX      source/core/board/nestopia-NstBoardUnlMortalKombat2.o
  CXX      source/core/board/nestopia-NstBoardKonamiVsSystem.o
  CXX      source/core/board/nestopia-NstBoardBandaiKaraokeStudio.o
  CXX      source/core/board/nestopia-NstBoardBtlAx5705.o
  CXX      source/core/board/nestopia-NstBoardBtl2708.o
  CXX      source/core/board/nestopia-NstBoardBandaiLz93d50.o
  CXX      source/core/board/nestopia-NstBoardEvent.o
  CXX      source/core/board/nestopia-NstBoardFutureMedia.o
  CXX      source/core/board/nestopia-NstBoardBmcSuperBig7in1.o
  CXX      source/core/board/nestopia-NstBoardJyCompany.o
  CXX      source/core/board/nestopia-NstBoardSachenSa0036.o
  CXX      source/core/board/nestopia-NstBoardTengenRambo1.o
  CXX      source/core/board/nestopia-NstBoardFb.o
  CXX      source/core/board/nestopia-NstBoardBtlSmb3.o
  CXX      source/core/board/nestopia-NstBoardBmc15in1.o
  CXX      source/core/board/nestopia-NstBoardRumbleStation.o
  CXX      source/core/board/nestopia-NstBoardBmcFk23c.o
  CXX      source/core/board/nestopia-NstBoardUnlWorldHero.o
  CXX      source/core/board/nestopia-NstBoardBandaiDatach.o
  CXX      source/core/board/nestopia-NstBoardUnlXzy.o
  CXX      source/core/board/nestopia-NstBoardTxcPoliceman.o
  CXX      source/core/board/nestopia-NstBoardWaixing.o
  CXX      source/core/board/nestopia-NstBoardKonamiVrc3.o
  CXX      source/core/board/nestopia-NstBoardAe.o
  CXX      source/core/board/nestopia-NstBoardBtlSuperBros11.o
  CXX      source/core/board/nestopia-NstBoardBmc110in1.o
  CXX      source/core/board/nestopia-NstBoardBmcSuperVision16in1.o
  CXX      source/core/board/nestopia-NstBoardSunsoft4.o
  CXX      source/core/board/nestopia-NstBoardBmcCh001.o
  CXX      source/core/board/nestopia-NstBoardBmcSuper40in1.o
  CXX      source/core/board/nestopia-NstBoardAxRom.o
  CXX      source/core/board/nestopia-NstBoardKayH2288.o
  CXX      source/core/board/nestopia-NstBoardBmcGoldenCard6in1.o
  CXX      source/core/board/nestopia-NstBoardRcm.o
  CXX      source/core/board/nestopia-NstBoardNamcot34xx.o
  CXX      source/core/board/nestopia-NstBoardGxRom.o
  CXX      source/core/board/nestopia-NstBoardBmcMarioParty7in1.o
  CXX      source/core/board/nestopia-NstBoardMmc1.o
  CXX      source/core/board/nestopia-NstBoardNanjing.o
  CXX      source/core/board/nestopia-NstBoardBmcFamily4646B.o
  CXX      source/core/board/nestopia-NstBoardBtlT230.o
  CXX      source/core/board/nestopia-NstBoardMagicKidGoogoo.o
  CXX      source/core/board/nestopia-NstBoardMagicSeries.o
  CXX      source/core/board/nestopia-NstBoardAveNina.o
  CXX      source/core/board/nestopia-NstBoardMmc6.o
  CXX      source/core/board/nestopia-NstBoardKasing.o
  CXX      source/core/board/nestopia-NstBoardJalecoJf19.o
  CXX      source/core/board/nestopia-NstBoardZz.o
  CXX      source/core/board/nestopia-NstBoardHenggedianzi.o
  CXX      source/core/board/nestopia-NstBoardCneShlz.o
  CXX      source/core/board/nestopia-NstBoardKonamiVrc7.o
  CXX      source/core/board/nestopia-NstBoardBmc22Games.o
  CXX      source/core/board/nestopia-NstBoardBmcGamestarB.o
  CXX      source/core/board/nestopia-NstBoardUnlN625092.o
  CXX      source/core/board/nestopia-NstBoardBmc150in1.o
  CXX      source/core/board/nestopia-NstBoardBmcSuperHiK4in1.o
  CXX      source/core/board/nestopia-NstBoardBtlShuiGuanPipe.o
  CXX      source/core/board/nestopia-NstBoardCnePsb.o
  CXX      source/core/board/nestopia-NstBoardSuperGamePocahontas2.o
  CXX      source/core/board/nestopia-NstBoardSachenSa0037.o
  CXX      source/core/board/nestopia-NstBoardSunsoftFme7.o
  CXX      source/core/board/nestopia-NstBoardBmcBallgames11in1.o
  CXX      source/core/board/nestopia-NstBoardFukutake.o
  CXX      source/core/board/nestopia-NstBoardIremH3001.o
  CXX      source/core/board/nestopia-NstBoardTaitoTc0190fmcPal16r4.o
  CXX      source/core/board/nestopia-NstBoardTaitoTc0190fmc.o
  CXX      source/core/board/nestopia-NstBoardBmcGolden190in1.o
  CXX      source/core/board/nestopia-NstBoardQj.o
  CXX      source/core/board/nestopia-NstBoardBmcGamestarA.o
  CXX      source/core/board/nestopia-NstBoardBtlSmb2c.o
  CXX      source/core/board/nestopia-NstBoardSunsoft2.o
  CXX      source/core/board/nestopia-NstBoardWaixingFfv.o
  CXX      source/core/board/nestopia-NstBoardBtlDragonNinja.o
  CXX      source/core/board/nestopia-NstBoardSunsoft3.o
  CXX      source/core/board/nestopia-NstBoardRexSoftSl1632.o
  CXX      source/core/board/nestopia-NstBoardSachenTca01.o
  CXX      source/core/board/nestopia-NstBoardBtlTobidaseDaisakusen.o
  CXX      source/core/board/nestopia-NstBoardSomeriTeamSl12.o
  CXX      source/core/board/nestopia-NstBoardBmc31in1.o
  CXX      source/core/board/nestopia-NstBoardUnlKingOfFighters96.o
  CXX      source/core/board/nestopia-NstBoardAgci.o
  CXX      source/core/board/nestopia-NstBoardBmcVt5201.o
  CXX      source/core/board/nestopia-NstBoardCneDecathlon.o
  CXX      source/core/board/nestopia-NstBoardRexSoftDb5z.o
  CXX      source/core/board/nestopia-NstBoardWhirlwind.o
  CXX      source/core/board/nestopia-NstBoardBmcSuper22Games.o
  CXX      source/core/board/nestopia-NstBoardBandaiLz93d50ex.o
  CXX      source/core/board/nestopia-NstBoardSachenSa72007.o
  CXX      source/core/board/nestopia-NstBoardBmc1200in1.o
  CXX      source/core/board/nestopia-NstBoardNamcot163.o
  CXX      source/core/board/nestopia-NstBoardCony.o
  CXX      source/core/board/nestopia-NstBoardNihon.o
  CXX      source/core/nestopia-NstFds.o
  CXX      source/core/nestopia-NstVideoFilterScaleX.o
  CXX      source/core/nestopia-NstNsf.o
  CXX      source/core/nestopia-NstSoundPcm.o
  CXX      source/core/nestopia-NstCartridgeRomset.o
  CXX      source/core/nestopia-NstVideoFilterNtsc.o
  CXX      source/core/nestopia-NstChecksum.o
  CXX      source/core/nestopia-NstVideoFilterNtscCfg.o
  CXX      source/core/nestopia-NstCrc32.o
  CXX      source/common/nestopia-nstcommon.o
  CXX      source/common/nestopia-cheats.o
  CXX      source/common/nestopia-cli.o
  CXX      source/common/nestopia-config.o
  CXX      source/common/nestopia-video.o
  CXX      source/common/nestopia-input.o
  CXX      source/common/nestopia-ini.o
  CXX      source/common/nestopia-png.o
  CXX      source/sdl/nestopia-audio.o
source/sdl/audio.cpp: In function ‘void audio_output_sdl()’:
source/sdl/audio.cpp:67:35: error: ‘SDL_GetQueuedAudioSize’ was not declared in this scope
  while (SDL_GetQueuedAudioSize(dev) > (Uint32)bufsize) {
                                   ^
source/sdl/audio.cpp:70:52: error: ‘SDL_QueueAudio’ was not declared in this scope
  SDL_QueueAudio(dev, (const void*)audiobuf, bufsize);
                                                    ^
source/sdl/audio.cpp:72:32: error: ‘SDL_GetQueuedAudioSize’ was not declared in this scope
  if (SDL_GetQueuedAudioSize(dev) > (Uint32)(bufsize * 3)) { SDL_ClearQueuedAudio(dev); }
                                ^
source/sdl/audio.cpp:72:85: error: ‘SDL_ClearQueuedAudio’ was not declared in this scope
  if (SDL_GetQueuedAudioSize(dev) > (Uint32)(bufsize * 3)) { SDL_ClearQueuedAudio(dev); }
                                                                                     ^
Makefile:8151: recipe for target 'source/sdl/nestopia-audio.o' failed
make: *** [source/sdl/nestopia-audio.o] Error 1
```

**Comment by orbea** [comment]
What SDL2 version do you have? It builds fine with `SDL2-2.0.8` here in Slackware64-current.

You can also use the libretro nestopia core with RetroArch. You should be able to download it directly from the online core updater in RetroArch or alternatively you can build it with this repo.
```
cd libretro
make
```
It will then create a core library file (`nestopia_libretro.so`) which you can put in your RetroArch core directory or start directly with RetroArch.
```
retroarch -L /path/to/nestopia_libretro.so /path/to/rom
```

**Comment by inukaze** [comment]
in Devuan Jessie / Debian Jessie in the repositry the SDL2 version is 2.0.2

**Comment by orbea** [comment]
I can reproduce this with `SDL2-2.0.2`. I think your best bet is to update to a newer SDL2 version or use the libretro core.

**Comment by inukaze** [comment]
the retroarch just gave me "Segmetation Fault" for that i try with this.

**Comment by rdanbrook** [comment]
You need SDL 2.0.4 or above.

As for making it work with old software, I have no plans to do so. I have had people ask for GTK+2 in the past too. If you want to use an older operating system, older releases will work on that. If you want to run the latest commit, assume that code is written for the latest releases of the underlying libraries.
